language: go
go:
  - 1.5
  - tip
env:
  global:
    - GO15VENDOREXPERIMENT=1
  matrix:
    - notmuch_branch=release
    - notmuch_branch=master
matrix:
  allow_failures:
    - go: tip
    - env: notmuch_branch=master
before_install:
  - uname -a
  - cat /etc/lsb-release
  - go get -u golang.org/x/tools/cmd/cover
  - sudo apt-get update -qq
  - sudo apt-get install dtach libxapian-dev libgmime-2.6-dev libtalloc-dev python-sphinx ruby-dev

  # Notmuch requires zlib 1.2.5.2, unfortunately travis runs on Ubuntu 12.04LTS which
  # ships with zlib 1.2.3.3. We need to update to zlib 1.2.5.2 to be able to build.
  # TODO: Watch https://github.com/travis-ci/travis-ci/issues/2046 and remove
  #       this hack once travis-ci switches to Ubuntu 14.04
  - wget 'https://github.com/notmuch/travis-files/raw/master/zlib1g-dev_1.2.8.dfsg-1ubuntu1_amd64.deb'
  - wget 'https://github.com/notmuch/travis-files/raw/master/zlib1g_1.2.8.dfsg-1ubuntu1_amd64.deb'
  - sudo dpkg -i zlib1g-dev_1.2.8.dfsg-1ubuntu1_amd64.deb zlib1g_1.2.8.dfsg-1ubuntu1_amd64.deb
  - sudo apt-get install -f

  - git clone --depth=50 https://github.com/notmuch/notmuch.git -b $notmuch_branch
  - pushd notmuch
  - ./configure --prefix=/usr
  - sudo make install
  - popd
  - sudo rm -rf notmuch
script: make test
